version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  proxy:
    container_name: proxy
    build: ./proxy
    restart: always
    entrypoint: ["sh", "-c", "/run.sh"]
    volumes:
      - proxy-dhparams:/var/proxy
      - ssl-certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend

volumes:
  proxy-dhparams:
  ssl-certs:
