version: '3.8'
services:
  nextjs:
    container_name: nextjs
    build: ./nextjs
    ports:
      - 3000:3000
    volumes:
      - ./nextjs:/app

  proxy:
    container_name: proxy
    build: ./proxy
    restart: always
    volumes:
      - proxy-dhparams:/var/proxy
      - ssl-certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nextjs

volumes:
  proxy-dhparams:
  ssl-certs:
